<?php
/**
 * Image
 *
 * @copyright Copyright © 2019 Firebear Studio. All rights reserved.
 * @author    fbeardev@gmail.com
 */

namespace Rapidive\FixImage\Catalog\Model\View\Asset;

use Magento\Catalog\Model\Product\Media\ConfigInterface;
use Magento\Framework\Encryption\Encryptor;
use Magento\Framework\Encryption\EncryptorInterface;
use Magento\Framework\View\Asset\ContextInterface;
use Magento\Framework\View\Asset\LocalInterface;

/**
 * A locally available image file asset that can be referred with a file path
 *
 * This class is a value object with lazy loading of some of its data (content, physical file path)
 */
class Image extends \Magento\Catalog\Model\View\Asset\Image
{
    public function getUrl()
    {
        var_dump($this->getContext()->getPath());
        var_dump($this->getSourceFile());
        exit;
        exit;
        return parent::getUrl(); // TODO: Change the autogenerated stub
    }
}